directive @oneOf on INPUT_OBJECT
scalar Datetime

type Query {
    user(id: ID!): User
    users(ids: [ID!]!): [User]!
    findUser(
        filteringOptions: UserFilteringOptions,
        sortingOptions: [UserSortingOption!],
        page: Page
    ): [User!]!

    post(id: ID!): Post
    posts(ids: [ID!]): [Post]!
    findPost(
        filteringOptions: PostFilteringOptions,
        sortingOptions: [PostSortingOption!],
        page: Page
    ): [Post!]!
}

type User {
    id: ID!
    name: String!

    posts(
        filteringOptions: PostFilteringOptions,
        sortingOptions: [PostSortingOption!]
    ): [Post!]!
}

type Post {
    id: ID!
    content: String!
    creator: User!
    postGenerateRequest: PostGenerateRequest!
}

input Page {
    offset: Int!
    limit: Int
}

input UserFilteringOptions {
    nameExact: String
    nameFront: String
    namePartial: String
    nameBack: String
}

input PostFilteringOptions {
    creatorIds: [ID!]
    reactionNumMore: Int
    reactionNumLess: Int
}

input UserSortingOption @oneOf {
    nameAsc: Boolean
    getReactionNumAsc: Boolean
    giveReactionNumAsc: Boolean
}

input PostSortingOption @oneOf {
    idAsc: Boolean
    reactionNumAsc: Boolean
    creatorIdAsc: Boolean
    createdAtAsc: Boolean
}
